[model]
name = "applecider.models.HyraxBaselineCLS.HyraxBaselineCLS"

#[model.HyraxBaselineCLS]

[data_loader]
batch_size = 128

[data_request]
[data_request.train.data]
dataset_class = "applecider.datasets.photo_dataset.PhotoEventsDataset"
data_location = "../../../data/photo_events/train/"
fields = ["photometry", "label", "mean", "std"]
primary_id_field = "object_id"
split_fraction = 0.8
[data_request.train.data.dataset_config.applecider.photo_dataset]
manifest_path = "../../../data/photo_events/manifest_train.csv"

[data_request.validate.data]
#[data_request.dont_use.data]
dataset_class = "applecider.datasets.photo_dataset.PhotoEventsDataset"
data_location = "../../../data/photo_events/val/"
fields = ["photometry", "label", "mean", "std"]
primary_id_field = "object_id"
split_fraction = 0.2
[data_request.validate.data.dataset_config.applecider.photo_dataset]
manifest_path = "../../../data/photo_events/manifest_val.csv"

[data_request.infer.data]
dataset_class = "applecider.datasets.photo_dataset.PhotoEventsDataset"
data_location = "../../../data/photo_events/test/"
fields = ["photometry", "mean", "std"]
primary_id_field = "object_id"
[data_request.infer.data.dataset_config.applecider.photo_dataset]
manifest_path = "../../../data/photo_events/manifest_test.csv"
use_oversampling = false

[train]
epochs = 3

[optimizer]
name = "torch.optim.Adam"
lr = 0.0001